### ISSUE TITLE
Broken Docker image

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.flaw-sleuth#4]
The Docker image we've [published on ghcr.io][v0.1.0] is broken. When started in Docker, the app displays an error and the logs report

```log
2022-07-27 08:31:03.416 INFO    matplotlib.font_manager: generated new fontManager

  You can now view your Streamlit app in your browser.

  Network URL: http://172.18.0.3:8501
  External URL: http://83.79.100.214:8501

2022-07-27 08:32:02.387 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/streamlit/scriptrunner/script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
  File "/app/streamlit-app.py", line 1, in <module>
    from flawsleuth.runner import run
  File "/app/flawsleuth/runner.py", line 1, in <module>
    from flawsleuth.ai import predict, kalman_forecast
  File "/app/flawsleuth/ai.py", line 30, in <module>
    model_repeat = joblib.load ( ANOMALY_MODEL_PATH_FROM_ROOT_REPEAT )
  File "/usr/local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 118
```

[v0.1.0]: https://github.com/c0c0n3/kitt4sme.flaw-sleuth/pkgs/container/kitt4sme.flaw-sleuth/29674786?tag=v0.1.0

**Comment by c0c0n3** [comment]
The problem is that PR #3 added `data/cls_new.joblib` to the repo as a [Git LFS][lfs] reference---the file was too large to add it to the GitHub repo directly, so we had to use LFS. Now the GitHub publish pipeline checks out the GitHub repo but doesn't resolve the reference. So when the Docker build kicks in, what gets added to the image is the reference, not the actual file. In fact, if you shell into the image you can see that

```console
$ docker exec -it 9a6169ebe3dc sh
# pwd
/app
# ls -al data   
total 20072
drwxr-xr-x 2 root root     4096 Jul 25 14:40 .
drwxr-xr-x 1 root root     4096 Jul 25 14:40 ..
-rw-r--r-- 1 root root   885182 Jul 25 14:37 anomaly_detection.pkl
-rw-r--r-- 1 root root      134 Jul 25 14:37 cls_new.joblib
-rw-r--r-- 1 root root    60816 Jul 25 14:37 data.npz
-rw-r--r-- 1 root root 19249306 Jul 25 14:37 ifor_cls_new.joblib
-rw-r--r-- 1 root root    10609 Jul 25 14:37 kalman_update.pf
-rw-r--r-- 1 root root     2143 Jul 25 14:37 kalman_update_old.pf
-rw-r--r-- 1 root root      815 Jul 25 14:37 scaler_new.joblib
-rw-r--r-- 1 root root   313376 Jul 25 14:37 xgb_fine_tuned.pkl
# cat data/cls_new.joblib
version https://git-lfs.github.com/spec/v1
oid sha256:82b6f0e90513842fedc23525c0c4277eca50f28085aba24122d9a47413019607
size 142247914
``` 

[lfs]: https://git-lfs.github.com/
